services:
  web:
    build: .
    container_name: snippetbin-web
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_ADDR=snippetbin-redis:6379
      - DB_ADDR=postgres://admin:adminpassword@snippetbin-db:5432/snippetbin?sslmode=disable
    volumes:
      - ./tls:/app/tls
  db:
    image: postgres:latest
    container_name: snippetbin-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: snippetbin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: snippetbin-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    container_name: redis-commander-snippetbin
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  db_data:


